x-airflow-common:
  &airflow-common
  image: apache/airflow:2.8.1
  user: "50000:0"
  environment:
    AIRFLOW_HOME: /opt/airflow
    AIRFLOW__CORE__EXECUTOR: SequentialExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__FERNET_KEY: ""
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
    AWS_DEFAULT_REGION: us-east-1
    AWS_SHARED_CREDENTIALS_FILE: /home/airflow/.aws/credentials
    AWS_CONFIG_FILE: /home/airflow/.aws/config
  volumes:
    - airflow_data:/opt/airflow
    - ./dags:/opt/airflow/dags
    - ./plugins:/opt/airflow/plugins
    - airflow_logs:/opt/airflow/logs
    - /c/Users/erika.ruiz/.aws:/home/airflow/.aws:ro

services:
  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "
      airflow db init &&
      airflow users create
      --username admin
      --password admin
      --firstname admin
      --lastname user
      --role Admin
      --email admin@local || true
      "

  airflow-webserver:
    <<: *airflow-common
    command: >
      bash -c "
      airflow webserver
      "
    ports:
      - "8080:8080"

  airflow-scheduler:
    <<: *airflow-common
    command: >
      bash -c "
      airflow scheduler
      "

volumes:
  airflow_data:
  airflow_logs: